<?php

class CategoryDAO extends Conexao
{
    public function __constructor()
    {
        parent::__constructor(); // TODO: Change the autogenerated stub
    }

    public function getCategories($id = "") {
        $filter =  ($id != "") ? "where id=?" : "";
        $sql = "select * from category $filter";
        $stmt = $this->connection->prepare($sql);
        if($filter != "") {
            $stmt->bind_param("s", $id);
        }
        $stmt->execute();
        $categories = $this->createTableArray($stmt->get_result());
        return  $categories;
    }
    public function addCategory($category) {
        $sql="INSERT INTO category (id,description) VALUES (default,?)";
        $stmt = $this->connection->prepare($sql);
        $stmt->bind_param("s", $category['description']);
        $stmt->execute();
        return  $stmt->affected_rows;
    }
    public function updateCategory($category) {
        $sql="UPDATE category SET description=? WHERE id=?";
        $stmt = $this->connection->prepare($sql);
        $stmt->bind_param("ss", $category['description'],$category['id']);
        $stmt->execute();
        return  $stmt->affected_rows;
    }
    public function getCategoryByDescription($category) {
        $nParams = "s";
        $filter = "";
        $params = array();
        $params[] = $category['description'];
        if(isset($category['id']) and $category['id'] != "") {
            $filter = " and id != ?";
            $nParams.="s";
            $params[] = $category['id'];
        }

        $sql="SELECT * FROM category WHERE description like ? $filter";
        $stmt = $this->connection->prepare($sql);
        $stmt->bind_param($nParams, ...$params);
        $stmt->execute();
        $this->resultado = $stmt->get_result();
        return  $this->resultado;
    }
}
