<?php

class CategoryDAO extends Conexao
{
    public function __constructor()
    {
        parent::__constructor(); // TODO: Change the autogenerated stub
    }

    public function getCategories($id = "") {
        $filter =  ($id != "") ? "where id=?" : "";
        $sql = "select * from category $filter";
        $stmt = $this->connection->prepare($sql);
        if($filter != "") {
            $stmt->bind_param("s", $id);
        }
        $stmt->execute();
        $categories = $this->createTableArray($stmt->get_result());
        return  $categories;
    }
    public function addCategory($category) {
        $sql="INSERT INTO category (id,description) VALUES (default,?)";
        $stmt = $this->connection->prepare($sql);
        $stmt->bind_param("s", $category['description']);
        $stmt->execute();
        return  $stmt->affected_rows;
    }
}