<?php

class LoginDAO extends Conexao
{
    public function __constructor()
    {
        parent::__constructor(); // TODO: Change the autogenerated stub
    }

    public function getUsers($roles = []) {
        $in = implode("','",$roles);
        $sql = "select * from client where role in ('$in')";
        $response = [];
        $users = $this->createTableArray($this->query($sql));

        forEach($users as $user) {
            $response[$user['name']] = $user['password'];
        }
        return $response;
    }
    public function register($user) {
        $sql="INSERT INTO client (id,name,password,email,complete_name,role) VALUES (default,?,?,?,?,'client')";
        $stmt = $this->connection->prepare($sql);
        $stmt->bind_param("ssss", $user['name'], $user['password'] , $user['email'], $user['complete-name'] );
        $stmt->execute();

        return  $stmt->affected_rows;
    }
    public function findUserByNameOrEmail($user) {
        $sql="SELECT * FROM client WHERE name=? or email=?";
        $stmt = $this->connection->prepare($sql);
        $stmt->bind_param("ss", $user['name'] , $user['email'] );
        $stmt->execute();
        $this->resultado = $stmt->get_result();
        return $this->resultado;
    }
    public function validate($user){
        $sql="SELECT *
		  	    FROM client
		  	   WHERE name=? AND password=? AND role=?";
        $stmt = $this->connection->prepare($sql);
        $stmt->bind_param("sss", $user['name'], $user['password'],$user['role']);
        $stmt->execute();
        return $this->createLineArray($stmt->get_result());
    }
    public function updateUserPassword($name,$pass) {
        $sql="UPDATE
             client
           SET password=? WHERE name=? ";
        $stmt = $this->connection->prepare($sql);
        $stmt->bind_param("ss", $pass, $name);
        $stmt->execute();
        return  $stmt->affected_rows;
    }
}
